"""
NSynth dataset loader with ADSR pseudo-labels.

Expects a data directory produced by run_pseudo_label.py:
    data/nsynth_estimated/
        metadata.jsonl   ← one JSON per line (same schema as SyntheticClip)
        (audio files referenced by absolute path from original NSynth download)

NSynth pitched instruments only (piano, strings, brass, guitar, etc.).
No percussion — drums/foley wait for Phase 6 (Option B diffusion model).
"""

from __future__ import annotations
import json
import torch
import torchaudio
import soundfile as sf
from pathlib import Path
from torch.utils.data import Dataset

SAMPLE_RATE = 48000

# NSynth instrument families (index → name)
NSYNTH_FAMILIES = {
    0: "piano", 1: "mallet", 2: "organ", 3: "guitar", 4: "bass",
    5: "strings", 6: "reed", 7: "flute", 8: "brass", 9: "synth_lead", 10: "vocal",
}
# Exclude percussion families (none in NSynth by design — it's all pitched)
# Exclude synth_lead and vocal for v1 (too ambiguous for ADSR pseudo-labels)
NSYNTH_EXCLUDED_FAMILIES = {9, 10}

NOTE_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]


def midi_to_hz(midi: int) -> float:
    return 440.0 * 2 ** ((midi - 69) / 12.0)


def midi_to_note_name(midi: int) -> str:
    octave = midi // 12 - 1
    note = NOTE_NAMES[midi % 12]
    return f"{note}{octave}"


class NSynthDataset(Dataset):
    """
    Loads NSynth clips with ADSR pseudo-labels generated by run_pseudo_label.py.

    Filters to clips above min_confidence threshold.
    Returns same dict schema as SyntheticDataset for trainer compatibility.
    """

    def __init__(
        self,
        data_dir: str,
        min_confidence: float = 0.5,
        max_duration_ms: float = 6000.0,
        sample_rate: int = SAMPLE_RATE,
    ) -> None:
        self.data_dir = Path(data_dir)
        self.sample_rate = sample_rate
        self.max_samples = int(max_duration_ms / 1000.0 * sample_rate)

        meta_path = self.data_dir / "metadata.jsonl"
        self.records: list[dict] = []
        with open(meta_path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                rec = json.loads(line)
                if rec.get("adsr_confidence", 0.0) >= min_confidence:
                    self.records.append(rec)

        print(f"NSynthDataset: {len(self.records)} clips above confidence {min_confidence}")

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, idx: int) -> dict:
        rec = self.records[idx]
        audio_path = rec["audio_path"]   # absolute path set by run_pseudo_label.py

        data, sr = sf.read(str(audio_path), dtype="float32")
        waveform = torch.from_numpy(data)
        if waveform.dim() > 1:
            waveform = waveform.mean(dim=-1)   # stereo → mono
        if sr != self.sample_rate:
            waveform = torchaudio.functional.resample(
                waveform.unsqueeze(0), sr, self.sample_rate
            ).squeeze(0)

        # Pad or trim
        if waveform.shape[0] < self.max_samples:
            waveform = torch.nn.functional.pad(
                waveform, (0, self.max_samples - waveform.shape[0])
            )
        else:
            waveform = waveform[:self.max_samples]

        return {
            "audio":          waveform,
            "f0_hz":          torch.tensor(midi_to_hz(rec["pitch_midi"]), dtype=torch.float32),
            "A":              torch.tensor(rec["A_ms"],       dtype=torch.float32),
            "D":              torch.tensor(rec["D_ms"],       dtype=torch.float32),
            "S":              torch.tensor(rec["S_level"],    dtype=torch.float32),
            "R":              torch.tensor(rec["R_ms"],       dtype=torch.float32),
            "velocity":       torch.tensor(rec.get("velocity", 1.0),          dtype=torch.float32),
            "note_duration":  torch.tensor(rec.get("note_duration", 1000.0),  dtype=torch.float32),
            "text_prompt":    rec.get("text_prompt", ""),
            "adsr_confidence": torch.tensor(rec.get("adsr_confidence", 1.0), dtype=torch.float32),
        }


class MixedDataset(Dataset):
    """
    Combines SyntheticDataset and NSynthDataset at a fixed mixing ratio.

    At each __getitem__ call, randomly draws from synthetic (with probability
    synthetic_ratio) or NSynth. Both datasets are sampled with replacement so
    neither runs out first.

    Epoch length = len(synthetic_dataset) (keeps training step count consistent
    with Stage 2 which used only synthetic data).
    """

    def __init__(
        self,
        synthetic_dataset: Dataset,
        nsynth_dataset: Dataset,
        synthetic_ratio: float = 0.7,
    ) -> None:
        self.synthetic = synthetic_dataset
        self.nsynth    = nsynth_dataset
        self.synthetic_ratio = synthetic_ratio

    def __len__(self) -> int:
        return len(self.synthetic)

    def __getitem__(self, idx: int) -> dict:
        if torch.rand(1).item() < self.synthetic_ratio:
            i = idx % len(self.synthetic)
            return self.synthetic[i]
        else:
            i = torch.randint(len(self.nsynth), (1,)).item()
            return self.nsynth[i]
